name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.7.4-alpine

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Check formatting with black
        run: |
          black --line-length 120 --target-version py37 --check .
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: ro_help.settings.dev
        run: pytest ro_help
