name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.7.7-buster

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==19.10b0
      - name: Check formatting with black
        run: |
          black --line-length 120 --target-version py37 --check .
