name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    container: code4ro/aid-management-hub

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Check formatting with black
        run: |
          black --line-length 120 --target-version py37 --check .
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: aid_management.settings.dev
        run: pytest aid_management
